//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlennMessageBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICLE()
        {
            this.ARTICLEREPLY = new HashSet<ARTICLEREPLY>();
        }
    
        public int ID { get; set; }
        public int FORUM_ID { get; set; }
        public string TITLE { get; set; }
        public string BODY { get; set; }
        public System.DateTime BUD_DTM { get; set; }
        public System.DateTime UPD_DTM { get; set; }
        public string AUTHOR { get; set; }
    
        public virtual Forum Forum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICLEREPLY> ARTICLEREPLY { get; set; }
    }
}
